New in CSr17:

1) Updates for +TSora

New in CSr16:

1) TSora - A timestamping protocal which disallows "op hacking" and nick
        colliding.
        Thanks to Roger Espel Llima <espel@clipper.ens.fr>

2) Better kline checking - This should be faster, and use less CPU
        Thanks to Philippe Levan <levan@epix.net>

3) Fixed /rehash not working when the server is in dog3's High Traffic Mode

4) Added nicknames to users.log

5) Upped values in dog3.h, config.h, and hash.c for larger sendqs and a
   bigger hash table for clients.


